# DESCRIPTION: GitLab CI/CD for libRetro (NOT FOR GitLab-proper)

##############################################################################
################################# BOILERPLATE ################################
##############################################################################

# Core definitions
.core-defs:
  variables:
    GIT_SUBMODULE_STRATEGY: recursive
    CORENAME: play
    API_LEVEL: 19
    CORE_ARGS: -DBUILD_LIBRETRO_CORE=ON -DBUILD_PLAY=OFF -DENABLE_AMAZON_S3=off -DBUILD_TESTS=OFF
    EXTRA_PATH: Source/ui_libretro

.core-defs-win:
  extends:
    .core-defs
  variables:
    EXTRA_PATH: Source/ui_libretro/Release

# Inclusion templates, required for the build to work

include:
  ################################## DESKTOPS ################################    
  # Linux
  - project: 'libretro-infrastructure/ci-templates'
    file: '/linux-cmake.yml'

  # Windows
  - project: 'libretro-infrastructure/ci-templates'
    file: '/windows-cmake-msvc19.yml'

  # MacOS
  - project: 'libretro-infrastructure/ci-templates'
    file: 'osx-cmake-x86.yml'

  # MacOS
  - project: 'libretro-infrastructure/ci-templates'
    file: 'osx-cmake-arm64.yml'

  ################################## CELLULAR ################################    
  # Android
  - project: 'libretro-infrastructure/ci-templates'
    file: '/android-cmake.yml'

# Stages for building
stages:
  - build-prepare
  - build-shared
  - build-static

##############################################################################
#################################### STAGES ##################################
##############################################################################
#
################################### DESKTOPS #################################    
# Linux 64-bit 
libretro-build-linux-x64:
  extends:
    - .libretro-linux-cmake-x86_64
    - .core-defs

# Linux 32-bit
libretro-build-linux-i686:
  extends:
    - .libretro-linux-cmake-x86
    - .core-defs

# Windows 64-bit
libretro-build-windows-x64:
  extends:
    - .libretro-windows-msvc19-cmake-x86_64
    - .core-defs-win

# Windows 32-bit
libretro-build-windows-i686:
  extends:
    - .libretro-windows-msvc19-cmake-x86
    - .core-defs-win

# MacOS 64-bit
libretro-build-osx-x64:
  extends:
    - .libretro-osx-cmake-x86
    - .core-defs

# MacOS arm 64-bit
libretro-build-osx-arm64:
  extends:
    - .libretro-osx-cmake-arm64
    - .core-defs

################################### CELLULAR #################################
# Android ARMv7a
#android-armeabi-v7a:
#  extends:
#    - .libretro-android-cmake-armeabi-v7a
#    - .core-defs

# Android ARMv8a
android-arm64-v8a:
  extends:
    - .libretro-android-cmake-arm64-v8a
    - .core-defs

# Android 64-bit x86
android-x86_64:
  extends:
    - .libretro-android-cmake-x86_64
    - .core-defs

# Android 32-bit x86
android-x86:
  extends:
    - .libretro-android-cmake-x86
    - .core-defs

################################### CONSOLES #################################
