name: Build JavaScript

on: [push, pull_request]
jobs:
  build_js:
    runs-on: ubuntu-latest
    steps:
      - name: Setup Emscripten
        uses: mymindstorm/setup-emsdk@v12
        with:
          version: 3.1.19
      - name: Checkout
        uses: actions/checkout@v3
        with:
          submodules: recursive
          fetch-depth: 0
      - name: Generate CMake Project
        run: |
          mkdir build
          cd build
          emcmake cmake .. -DCMAKE_BUILD_TYPE=Release -DBUILD_TESTS=OFF -DBUILD_PLAY=ON -DBUILD_PSFPLAYER=ON -DUSE_QT=OFF
      - name: Build Native Code
        run: |
          cd build
          cmake --build . --config Release -j $(nproc)
      # Setup Node.js since Emscripten can override the node's version.
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16.17
      - name: Run CodeGenTestSuite
        run: |
          cd $GITHUB_WORKSPACE/deps/CodeGen/js
          npm install
          tsc
          cd $GITHUB_WORKSPACE/build/Source/ui_js/Source/CodeGen
          node --experimental-wasm-threads --experimental-wasm-simd $GITHUB_WORKSPACE/deps/CodeGen/js/out/index.js
      - name: Build Play Browser
        run: |
          cd js/play_browser
          cp ../../build/Source/ui_js/Play.js ./src/
          cp ../../build/Source/ui_js/Play.wasm ./public/
          cp ../../build/Source/ui_js/Play.js ./public/
          cp ../../build/Source/ui_js/Play.worker.js ./public/
          export REACT_APP_VERSION=$(git describe)
          npm install
          npm run build
      - name: Build PsfPlayer Browser
        run: |
          cd js/psfplayer_browser
          cp ../../build/tools/PsfPlayer/Source/ui_js/PsfPlayer.js ./src/
          cp ../../build/tools/PsfPlayer/Source/ui_js/PsfPlayer.wasm ./public/
          cp ../../build/tools/PsfPlayer/Source/ui_js/PsfPlayer.js ./public/
          cp ../../build/tools/PsfPlayer/Source/ui_js/PsfPlayer.worker.js ./public/
          export REACT_APP_VERSION=$(git describe)
          npm install
          npm run build
